version: "3.8"

services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "trading"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      
  trading-engine:
    image: n960321/trading-engine:latest
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./trading-engine/config:/app/configs
    depends_on:
      mysql:
        condition: service_healthy

        
